### ISSUE TITLE
Add CsvFieldOrder annotation

### ISSUE THREAD

**Issue by mlvn23** [uniVocity/univocity-parsers#27]
The one thing I really liked about this library is the Bean annotation feature! With it, I was able to write a generic toCsv and fromCsv routines similar to how you could use Jackson without passing metadata (unlike SuperCsv). The only quirk I found was declaring the headers to determine which fields to write and in what order. I believe this can be enhanced by introducing a CsvFieldOrder annotation (which I did) at the class level of the Bean. 

I did it like this (it's in Scala, but I think you get the idea):

```
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
public @interface CsvFieldOrder {
    String[] fields();
}

    def toCsv[T: Manifest](records: Seq[T], filename: String, headers: Option[Seq[String]] = None)
        (implicit tag: ClassTag[T]): Unit = {

        val cls = tag.runtimeClass.asInstanceOf[Class[T]]
        val processor = new BeanWriterProcessor[T](cls)

        val settings = new CsvWriterSettings
        settings.setRowWriterProcessor(processor)
        headers.map { h =>
            settings.setHeaders(h: _*)
        } getOrElse {
            val order = cls.getAnnotation(classOf[CsvFieldOrder])
            if (order == null) {
                throw new IllegalArgumentException(
                    "CsvFieldOrder annotation not found and headers is none"
                )
            } else {
                settings.setHeaders(order.fields():_*)
            }
        }

        val outputStream = new FileOutputStream(filename)
        val outputWriter = new OutputStreamWriter(outputStream)
        val w = new CsvWriter(outputWriter, settings)
        w.writeHeaders()
        w.processRecordsAndClose(records.asJava)

    }
```

**Comment by jbax** [comment]
Thanks for the suggestion. It will be implemented, and there's much more to be explored here. Give me a few hours to build support for this (among a few other things associated to it).

**Comment by jbax** [comment]
Implemented in the following commit: https://github.com/uniVocity/univocity-parsers/commit/a39d22e58a4b28c57d6c40b8c533cdb47f8d6d0b

The [Headers](https://github.com/uniVocity/univocity-parsers/blob/master/src/main/java/com/univocity/parsers/annotations/Headers.java) annotation allows you to specify the headers from your java bean class.

You can also control whether to write/extract headers. The settings classes for parsers/writers were modified to allow automatic configuration based on other settings. Currently, if a bean processor is used, the a recommended set of defaults (including headers if you defined them) will be used if nothing has been explicitly defined by the user.

I released a SNAPSHOT of version 1.6.0 for you to test this. Please reopen the issue if you find any problem.

Thank you for your suggestion and for using our parsers!

**Comment by mlvn23** [comment]
Thanks again for the quick turn-around! I'll give it a try.

**Comment by derekmahar** [comment]
Jeronimo, did you release 1.6.0-SNAPSHOT to a Maven repository?  My Maven build still can't find this  version.

**Comment by derekmahar** [comment]
I see 1.6.0-SNAPSHOT at https://oss.sonatype.org/content/repositories/snapshots/com/univocity/univocity-parsers/1.6.0-SNAPSHOT/.  Will add it again to my Maven build and see if it's successful.

**Comment by jbax** [comment]
You might need to add this to your pom.xml:

```
        <distributionManagement>
		<snapshotRepository>
			<id>ossrh</id>
			<url>https://oss.sonatype.org/content/repositories/snapshots</url>
		</snapshotRepository>
	</distributionManagement>

```

**Comment by derekmahar** [comment]
I had to make a few changes to my Maven project.

First, instead of your suggestion to add a `<snapshotRepository>`, I instead added a `<repository>` with snapshots enabled:

```xml
	<repositories>
		<repository>
			<id>sonatype.snapshots</id>
			<name>Sonatype Snapshot Repository</name>
			<releases>
				<enabled>false</enabled>
			</releases>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
			<url>https://oss.sonatype.org/content/repositories/snapshots</url>
		</repository>
	</repositories>
```

Then I added Maven plugin `maven-dependency-plugin` to my pom.xml:

```xml
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<version>2.10</version>
			</plugin>
		</plugins>
```

Then I deleted copy of univocity-parsers-1.6.0-SNAPSHOT.jar in my local Maven repository which also retrieved the copy from the Sonatype repository:

```
derek@derek-lubuntu:~/Projects/fatca$ mvn dependency:purge-local-repository -DsnapshotsOnly=true
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building fatca 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.10:purge-local-repository (default-cli) @ fatca ---
Downloading: https://oss.sonatype.org/content/repositories/snapshots/com/univocity/univocity-parsers/1.6.0-SNAPSHOT/univocity-parsers-1.6.0-20150511.130610-2.pom
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/com/univocity/univocity-parsers/1.6.0-SNAPSHOT/univocity-parsers-1.6.0-20150511.130610-2.pom (8 KB at 11.5 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/com/univocity/univocity-parsers/1.6.0-SNAPSHOT/univocity-parsers-1.6.0-20150511.130610-2.jar
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/com/univocity/univocity-parsers/1.6.0-SNAPSHOT/univocity-parsers-1.6.0-20150511.130610-2.jar (160 KB at 458.7 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.692s
[INFO] Finished at: Mon May 11 12:22:17 EDT 2015
[INFO] Final Memory: 13M/60M
[INFO] ------------------------------------------------------------------------
```

Finally, I successfully rebuilt and ran my unit tests, one of which refers to new class [`DataParsingException`](https://github.com/uniVocity/univocity-parsers/blob/2fa0b0aa404632ca19be811483c0783c3cada846/src/main/java/com/univocity/parsers/common/DataProcessingException.java) that you introduced in #26:

```
derek@derek-lubuntu:~/Projects/fatca$ mvn test
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building fatca 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: https://oss.sonatype.org/content/repositories/snapshots/com/univocity/univocity-parsers/1.6.0-SNAPSHOT/maven-metadata.xml
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/com/univocity/univocity-parsers/1.6.0-SNAPSHOT/maven-metadata.xml (2 KB at 0.1 KB/sec)
[INFO] 
[INFO] --- jaxb2-maven-plugin:1.5:xjc (default) @ fatca ---
[INFO] No changes detected in schema or binding files - skipping source generation.
[INFO] 
[INFO] --- maven-resources-plugin:2.3:resources (default-resources) @ fatca ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ fatca ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.3:testResources (default-testResources) @ fatca ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 7 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:testCompile (default-testCompile) @ fatca ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.10:test (default-test) @ fatca ---
[INFO] Surefire report directory: /home/derek/Projects/fatca/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.opessoftware.fatca.file.xml.FatcaReportXMLImplTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.08 sec
Running com.opessoftware.fatca.xml.crypt.XMLProcessorTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Running com.opessoftware.fatca.model.reader.csv.CsvAccountReaderTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.047 sec
Running com.opessoftware.fatca.model.reader.csv.CsvRowListReaderTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.014 sec
Running com.opessoftware.fatca.model.reader.csv.CsvFatcaReportFormReaderTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.067 sec

Results :

Tests run: 6, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 22.943s
[INFO] Finished at: Mon May 11 12:24:21 EDT 2015
[INFO] Final Memory: 12M/60M
[INFO] ------------------------------------------------------------------------
```

**Comment by mlvn23** [comment]
@jbax, extending this idea further, I think it would be great if we have a generic toCsv and fromCsv routine that uses some sane default settings that one could use out of the box (or maybe specify some predefined settings like settings.Excel). It would be very handy, and from PR perspective, it's very appealing to serialize / de-serialize in one line of code:

```
    val x = CsvUtils.fromCsv[TradeLogBean]("test.csv")
    CsvUtils.toCsv[TradeLogBean](x, "test1.csv")
```
